<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["balance_income/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["balance_income/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Income</th>
            <th>Member</th>
            <th>Change Of Balance</th>
            <th>Before Of Balance</th>
            <th>After Of Balance</th>
            <th>Left Of Balance</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $balance_income): ?>
            <tr>
                <td><?php echo $balance_income->income_id ?></td>
            <td><?php echo $balance_income->member_id ?></td>
            <td><?php echo $balance_income->change_balance ?></td>
            <td><?php echo $balance_income->before_balance ?></td>
            <td><?php echo $balance_income->after_balance ?></td>
            <td><?php echo $balance_income->left_balance ?></td>

                <td><?php echo $this->tag->linkTo(["balance_income/edit/" . $balance_income->income_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["balance_income/delete/" . $balance_income->income_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("balance_income/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("balance_income/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("balance_income/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("balance_income/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
